# Generated by Django 2.0.7 on 2020-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='自增唯一id')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('info', models.CharField(max_length=100, verbose_name='自我介绍')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
